# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    fragments: { path: /_fragment }
    esi: true
    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: ~

        gc_probability:       1
        gc_divisor:           1
        
        gc_maxlifetime: 5

        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 31536000
        #cookie_path: '%kernel.project_dir%/var/cookies/%kernel.environment%'
        
    #error_controller: App\Controller\ErrorController

    #esi: true
    #fragments: true
    
    router:
        default_uri: '%env(DEFAULT_URI)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
