###> JUST EXAMPLE, copy it into your config ###

gs_generic_parts:
    locale:                     '%env(LOCALE)%'

    timezone:                   '%env(TIMEZONE)%'
    
    timezone_session_name:      '%env(TIMEZONE_SESSION_NAME)%'