gs_service:
    locale: '%env(APP_LOCALE)%'
    timezone: '%env(APP_TIMEZONE)%'
#    load_packs_configs:
#    -   pack_name:      'gs_service'
#        pack_rel_path:  'config/packages'
#        does_not_exist_mess: 'your_namespace.exception.file_must_exist' # (NOT REQUIRED) Translated message    