framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        #failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'
            
            ###> ASYNC TRANSPORTS ###
            async_high_priority:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: high_priority
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            ###< ASYNC TRANSPORTS ###
            
        routing:
            'App\Messenger\*': async
            'App\Messenger\AsyncMessageHighPriorityInterface': async_high_priority
            #'App\Messenger\Notifier\SendEmail':
            #-   sync
            
            #'*': sync

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
