services:

    ###> CARBON IMMUTABLE ###
    
    app.ru_12_carbon:
        parent: gs_service.carbon_factory_immutable
        arguments:
            $settings:
                locale: ru
                timezone: '+1200'
    
    app.en_utc_carbon:
        parent: gs_service.carbon_factory_immutable
        arguments:
            $settings:
                locale: en_US
                timezone: '+0000'
    
    ###< CARBON IMMUTABLE ###
