twig:

    paths:
        '%kernel.project_dir%/vendor/grin-symfony/generic-parts-bundle':           GSGenericPartsBundle

    globals:
        gs_generic_parts:
            timezone_session_name:                      '%gs_generic_parts.timezone_session_name%'